### PR TITLE
Fix nits in generate.go

### PR DESCRIPTION
**Pull request by xun-cockroachlabs**
Added export of machine type to machinetype.txt and one type in azure.json, which was lost due to a merge issue. Added a few comments to make change clear.

Release note: none

### CODE REVIEW

**Comment by xun-cockroachlabs** [comment]
PTAL. I will merge after some test passes on the pr.

**Comment by ZhouXing19** [comment]
LGTM, maybe we can edit the commit message to "added export of machine type to machinetype.txt, and some other nits" to make it clear.

**Comment by xun-cockroachlabs** [comment]
@ZhouXing19 Modified the message per your comment. If you want to take another quick look? Thanks.

**Comment by ZhouXing19** [comment]
Oh I meant the commit message, not just the PR description. You can use ‘git commit —amend’ to change the commit message. Other than that, feel free to merge!

**Comment by xun-cockroachlabs** [comment]
I see, will change. TFTR!

**Pull request merged**
