### PR TITLE
add D*S_v4 and D*S_v5 

### PR DESCRIPTION
**Pull request by ZhouXing19**

### CODE REVIEW

**Comment by ZhouXing19** [comment]
@xun-cockroachlabs do I need to change azure's disk volumn to 1TB as well?

**Comment by ZhouXing19** [comment]
Have verified that machines can be created:

```
roachprod create jane-cldrprt22-Standard-D8s-v4-1185431031 -n 1 --lifetime 6h --clouds azure --azure-machine-type Standard_D8s_v4 --azure-locations=eastus --azure-availability-zone=2 --azure-volume-size=2500 --azure-disk-caching=read-only --local-ssd=false --azure-network-disk-type=premium-disk --label usage=cloud-report-2022
Creating cluster jane-cldrprt22-Standard-D8s-v4-1185431031 with 1 nodes
I211229 20:43:02.527769 11 roachprod/vm/azure/azure.go:1049  [-] 1  created Azure VNet "common" in "roachprod-vnets-eastus" with prefix 1
I211229 20:43:05.096185 13 roachprod/vm/azure/azure.go:1148  [-] 2  created Azure IP jane-cldrprt22-Standard-D8s-v4-1185431031-0001
I211229 20:43:05.917958 13 roachprod/vm/azure/azure.go:709  [-] 3  created NIC jane-cldrprt22-Standard-D8s-v4-1185431031-0001 10.1.0.9
I211229 20:43:05.918058 13 roachprod/vm/azure/azure.go:538  [-] 4  WARNING: increasing the OS volume size to minimally allowed 32GB
I211229 20:45:53.102134 13 roachprod/vm/azure/azure.go:214  [-] 5  created VM jane-cldrprt22-Standard-D8s-v4-1185431031-0001
jane-cldrprt22-Standard-D8s-v4-1185431031: [azure] 6h12m50s remaining
  jane-cldrprt22-Standard-D8s-v4-1185431031-0001	10.1.0.9	10.1.0.9	20.51.245.232
jane-cldrprt22-Standard-D8s-v4-1185431031: waiting for nodes to start.
generating ssh key.
distributing ssh key
retrieving hosts.
scanning hosts
distributing known_hosts
adding additional authorized keys
+ roachprod run jane-cldrprt22-Standard-D8s-v4-1185431031 -- tmux new -s cloud-report -d
+ create_west_cluster
+ roachprod create jane-cldrprt22-Standard-D8s-v4-1185431031-west -u jane -n 1 --lifetime 6h --clouds azure --azure-machine-type Standard_D8s_v4 --azure-locations=westus2 --azure-availability-zone=2 --azure-volume-size=2500 --azure-disk-caching=read-only --local-ssd=false --azure-network-disk-type=premium-disk --label usage=cloud-report-2022
Creating cluster jane-cldrprt22-Standard-D8s-v4-1185431031-west with 1 nodes
I211229 20:47:31.298199 227 roachprod/vm/azure/azure.go:1049  [-] 1  created Azure VNet "common" in "roachprod-vnets-westus2" with prefix 2
I211229 20:47:34.897822 228 roachprod/vm/azure/azure.go:1148  [-] 2  created Azure IP jane-cldrprt22-Standard-D8s-v4-1185431031-west-0001
I211229 20:47:36.265205 228 roachprod/vm/azure/azure.go:709  [-] 3  created NIC jane-cldrprt22-Standard-D8s-v4-1185431031-west-0001 10.2.0.14
I211229 20:47:36.265263 228 roachprod/vm/azure/azure.go:538  [-] 4  WARNING: increasing the OS volume size to minimally allowed 32GB
I211229 20:48:23.372886 228 roachprod/vm/azure/azure.go:214  [-] 5  created VM jane-cldrprt22-Standard-D8s-v4-1185431031-west-0001
jane-cldrprt22-Standard-D8s-v4-1185431031-west: [azure] 6h10m49s remaining
  jane-cldrprt22-Standard-D8s-v4-1185431031-west-0001	10.2.0.14	10.2.0.14	20.94.239.151
jane-cldrprt22-Standard-D8s-v4-1185431031-west: waiting for nodes to start..
generating ssh key.
distributing ssh key
retrieving hosts..
scanning hosts.
distributing known_hosts.
adding additional authorized keys.

roachprod create jane-cldrprt22-Standard-D8s-v5-1185431031 -n 1 --lifetime 6h --clouds azure --azure-machine-type Standard_D8s_v5 --azure-locations=eastus --azure-network-disk-type=premium-disk --azure-availability-zone=2 --azure-volume-size=2500 --azure-disk-caching=read-only --local-ssd=false --label usage=cloud-report-2022
Creating cluster jane-cldrprt22-Standard-D8s-v5-1185431031 with 1 nodes
I211229 20:42:50.893536 242 roachprod/vm/azure/azure.go:1049  [-] 1  created Azure VNet "common" in "roachprod-vnets-eastus" with prefix 1
I211229 20:42:53.253864 227 roachprod/vm/azure/azure.go:1148  [-] 2  created Azure IP jane-cldrprt22-Standard-D8s-v5-1185431031-0001
I211229 20:42:54.078414 227 roachprod/vm/azure/azure.go:709  [-] 3  created NIC jane-cldrprt22-Standard-D8s-v5-1185431031-0001 10.1.0.8
I211229 20:42:54.078505 227 roachprod/vm/azure/azure.go:538  [-] 4  WARNING: increasing the OS volume size to minimally allowed 32GB
I211229 20:43:40.434055 227 roachprod/vm/azure/azure.go:214  [-] 5  created VM jane-cldrprt22-Standard-D8s-v5-1185431031-0001
jane-cldrprt22-Standard-D8s-v5-1185431031: [azure] 6h15m50s remaining
  jane-cldrprt22-Standard-D8s-v5-1185431031-0001	10.1.0.8	10.1.0.8	20.51.245.224
jane-cldrprt22-Standard-D8s-v5-1185431031: waiting for nodes to start..
generating ssh key
distributing ssh key
retrieving hosts.
scanning hosts
distributing known_hosts
adding additional authorized keys
+ roachprod run jane-cldrprt22-Standard-D8s-v5-1185431031 -- tmux new -s cloud-report -d
+ create_west_cluster
+ roachprod create jane-cldrprt22-Standard-D8s-v5-1185431031-west -u jane -n 1 --lifetime 6h --clouds azure --azure-machine-type Standard_D8s_v5 --azure-locations=westus2 --azure-network-disk-type=premium-disk --azure-availability-zone=2 --azure-volume-size=2500 --azure-disk-caching=read-only --local-ssd=false --label usage=cloud-report-2022
Creating cluster jane-cldrprt22-Standard-D8s-v5-1185431031-west with 1 nodes
I211229 20:44:27.008511 56 roachprod/vm/azure/azure.go:1049  [-] 1  created Azure VNet "common" in "roachprod-vnets-westus2" with prefix 2
I211229 20:44:31.313250 80 roachprod/vm/azure/azure.go:1148  [-] 2  created Azure IP jane-cldrprt22-Standard-D8s-v5-1185431031-west-0001
I211229 20:44:32.389348 80 roachprod/vm/azure/azure.go:709  [-] 3  created NIC jane-cldrprt22-Standard-D8s-v5-1185431031-west-0001 10.2.0.9
I211229 20:44:32.389456 80 roachprod/vm/azure/azure.go:538  [-] 4  WARNING: increasing the OS volume size to minimally allowed 32GB
I211229 20:45:19.177797 80 roachprod/vm/azure/azure.go:214  [-] 5  created VM jane-cldrprt22-Standard-D8s-v5-1185431031-west-0001
jane-cldrprt22-Standard-D8s-v5-1185431031-west: [azure] 6h13m29s remaining
  jane-cldrprt22-Standard-D8s-v5-1185431031-west-0001	10.2.0.9	10.2.0.9	20.94.237.18
jane-cldrprt22-Standard-D8s-v5-1185431031-west: waiting for nodes to start..
generating ssh key.
distributing ssh key
retrieving hosts..
scanning hosts.
distributing known_hosts.
adding additional authorized keys.


roachprod create jane-cldrprt22-Standard-D32s-v4-1185431031 -n 1 --lifetime 6h --clouds azure --azure-machine-type Standard_D32s_v4 --azure-locations=eastus --azure-availability-zone=2 --azure-volume-size=2500 --azure-disk-caching=read-only --local-ssd=false --azure-network-disk-type=premium-disk --label usage=cloud-report-2022
Creating cluster jane-cldrprt22-Standard-D32s-v4-1185431031 with 1 nodes
I211229 20:42:38.164601 210 roachprod/vm/azure/azure.go:1049  [-] 1  created Azure VNet "common" in "roachprod-vnets-eastus" with prefix 1
I211229 20:42:40.100333 76 roachprod/vm/azure/azure.go:1148  [-] 2  created Azure IP jane-cldrprt22-Standard-D32s-v4-1185431031-0001
I211229 20:42:40.957195 76 roachprod/vm/azure/azure.go:709  [-] 3  created NIC jane-cldrprt22-Standard-D32s-v4-1185431031-0001 10.1.0.5
I211229 20:42:40.957253 76 roachprod/vm/azure/azure.go:538  [-] 4  WARNING: increasing the OS volume size to minimally allowed 32GB
I211229 20:45:27.686185 76 roachprod/vm/azure/azure.go:214  [-] 5  created VM jane-cldrprt22-Standard-D32s-v4-1185431031-0001
jane-cldrprt22-Standard-D32s-v4-1185431031: [azure] 6h13m11s remaining
  jane-cldrprt22-Standard-D32s-v4-1185431031-0001	10.1.0.5	10.1.0.5	20.51.245.145
jane-cldrprt22-Standard-D32s-v4-1185431031: waiting for nodes to start.
generating ssh key.
distributing ssh key
retrieving hosts.
scanning hosts
distributing known_hosts
adding additional authorized keys
+ roachprod run jane-cldrprt22-Standard-D32s-v4-1185431031 -- tmux new -s cloud-report -d
+ create_west_cluster
+ roachprod create jane-cldrprt22-Standard-D32s-v4-1185431031-west -u jane -n 1 --lifetime 6h --clouds azure --azure-machine-type Standard_D32s_v4 --azure-locations=westus2 --azure-availability-zone=2 --azure-volume-size=2500 --azure-disk-caching=read-only --local-ssd=false --azure-network-disk-type=premium-disk --label usage=cloud-report-2022
Creating cluster jane-cldrprt22-Standard-D32s-v4-1185431031-west with 1 nodes
I211229 20:47:13.230609 57 roachprod/vm/azure/azure.go:1049  [-] 1  created Azure VNet "common" in "roachprod-vnets-westus2" with prefix 2
I211229 20:47:16.930352 11 roachprod/vm/azure/azure.go:1148  [-] 2  created Azure IP jane-cldrprt22-Standard-D32s-v4-1185431031-west-0001
I211229 20:47:18.258603 11 roachprod/vm/azure/azure.go:709  [-] 3  created NIC jane-cldrprt22-Standard-D32s-v4-1185431031-west-0001 10.2.0.12
I211229 20:47:18.258661 11 roachprod/vm/azure/azure.go:538  [-] 4  WARNING: increasing the OS volume size to minimally allowed 32GB
I211229 20:48:05.243659 11 roachprod/vm/azure/azure.go:214  [-] 5  created VM jane-cldrprt22-Standard-D32s-v4-1185431031-west-0001
jane-cldrprt22-Standard-D32s-v4-1185431031-west: [azure] 6h11m38s remaining
  jane-cldrprt22-Standard-D32s-v4-1185431031-west-0001	10.2.0.12	10.2.0.12	20.94.239.69
jane-cldrprt22-Standard-D32s-v4-1185431031-west: waiting for nodes to start..
generating ssh key.
distributing ssh key
retrieving hosts..
scanning hosts.
distributing known_hosts.
adding additional authorized keys.


roachprod create jane-cldrprt22-Standard-D32s-v5-1185431031 -n 1 --lifetime 6h --clouds azure --azure-machine-type Standard_D32s_v5 --azure-locations=eastus --azure-network-disk-type=premium-disk --azure-availability-zone=2 --azure-volume-size=2500 --azure-disk-caching=read-only --local-ssd=false --label usage=cloud-report-2022
Creating cluster jane-cldrprt22-Standard-D32s-v5-1185431031 with 1 nodes
I211229 20:42:37.670735 196 roachprod/vm/azure/azure.go:1049  [-] 1  created Azure VNet "common" in "roachprod-vnets-eastus" with prefix 1
I211229 20:42:41.690417 81 roachprod/vm/azure/azure.go:1148  [-] 2  created Azure IP jane-cldrprt22-Standard-D32s-v5-1185431031-0001
I211229 20:42:42.331892 81 roachprod/vm/azure/azure.go:709  [-] 3  created NIC jane-cldrprt22-Standard-D32s-v5-1185431031-0001 10.1.0.6
I211229 20:42:42.331967 81 roachprod/vm/azure/azure.go:538  [-] 4  WARNING: increasing the OS volume size to minimally allowed 32GB
I211229 20:43:28.980252 81 roachprod/vm/azure/azure.go:214  [-] 5  created VM jane-cldrprt22-Standard-D32s-v5-1185431031-0001
jane-cldrprt22-Standard-D32s-v5-1185431031: [azure] 6h16m17s remaining
  jane-cldrprt22-Standard-D32s-v5-1185431031-0001	10.1.0.6	10.1.0.6	20.51.245.223
jane-cldrprt22-Standard-D32s-v5-1185431031: waiting for nodes to start..
generating ssh key
distributing ssh key
retrieving hosts.
scanning hosts
distributing known_hosts
adding additional authorized keys
+ roachprod run jane-cldrprt22-Standard-D32s-v5-1185431031 -- tmux new -s cloud-report -d
+ create_west_cluster
+ roachprod create jane-cldrprt22-Standard-D32s-v5-1185431031-west -u jane -n 1 --lifetime 6h --clouds azure --azure-machine-type Standard_D32s_v5 --azure-locations=westus2 --azure-network-disk-type=premium-disk --azure-availability-zone=2 --azure-volume-size=2500 --azure-disk-caching=read-only --local-ssd=false --label usage=cloud-report-2022
Creating cluster jane-cldrprt22-Standard-D32s-v5-1185431031-west with 1 nodes
I211229 20:44:13.432148 11 roachprod/vm/azure/azure.go:1049  [-] 1  created Azure VNet "common" in "roachprod-vnets-westus2" with prefix 2
I211229 20:44:19.490236 27 roachprod/vm/azure/azure.go:1148  [-] 2  created Azure IP jane-cldrprt22-Standard-D32s-v5-1185431031-west-0001
I211229 20:44:20.768069 27 roachprod/vm/azure/azure.go:709  [-] 3  created NIC jane-cldrprt22-Standard-D32s-v5-1185431031-west-0001 10.2.0.8
I211229 20:44:20.768127 27 roachprod/vm/azure/azure.go:538  [-] 4  WARNING: increasing the OS volume size to minimally allowed 32GB
I211229 20:45:07.726678 27 roachprod/vm/azure/azure.go:214  [-] 5  created VM jane-cldrprt22-Standard-D32s-v5-1185431031-west-0001
jane-cldrprt22-Standard-D32s-v5-1185431031-west: [azure] 6h13m44s remaining
  jane-cldrprt22-Standard-D32s-v5-1185431031-west-0001	10.2.0.8	10.2.0.8	20.94.236.178
jane-cldrprt22-Standard-D32s-v5-1185431031-west: waiting for nodes to start..
generating ssh key.
distributing ssh key
retrieving hosts..
scanning hosts.
distributing known_hosts.
adding additional authorized keys.
```

**Comment by xun-cockroachlabs** [comment]
Yes, we should change all vcpu8 disk to 1tb, including aws.

**Comment by ZhouXing19** [comment]
@xun-cockroachlabs done changing the volume for 8-core machines to 1tb. Could you give it a second look? Thanks!

**Comment by xun-cockroachlabs** [comment]
A suggestion: Either you move the aws disk change to this PR, or move the disk change for azure in this PR to the other disk change, this will make tracking change history easier for future readers. Ideally we should keep all disk change in one PR, but since gce disk was already merged, we can ignore that. That's the most clean way to submit the disk change.

**Comment by ZhouXing19** [comment]
@xun-cockroachlabs done. This one would be just add D*s machine, and to shrink the azure volume, check #93. Thanks!

**Comment by ZhouXing19** [comment]
Solved by #93

**Pull request closed without merging**
